kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "supermarket.name" . }}
data:
  spring.datasource.url: "jdbc:postgresql://host.private:5432/supermarket"
  spring.datasource.username: supermarket_admin
  spring.datasource.password: changeme
  spring.redis.host: "host.private"
  spring.redis.port: "6379"
