kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bouncer.fullname" . }}-config
data:
  spring.datasource.url: "jdbc:postgresql://host.private:5432/bouncer"
  spring.datasource.username: bouncer_admin
  spring.datasource.password: changeme
  spring.redis.host: "host.private"
  spring.redis.port: "6379"